spring.application.name=almacen3d

#BASE MYSQL
spring.datasource.url=jdbc:mysql://localhost:3306/XXX?createDatabaseIfNotExist=true
spring.datasource.username=
spring.datasource.password=
spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver